// <auto-generated />
using System;
using JIITPlacement.Models.App_Code;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JIITPlacement.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260920064916_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JIITPlacement.Models.App_Code.JobDocumentRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("DocumentIdentifier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocumentUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SysJobUuid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("posteddatetime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("updateddatetime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DocumentIdentifier")
                        .IsUnique();

                    b.HasIndex("SysJobUuid");

                    b.ToTable("JobDocuments");
                });

            modelBuilder.Entity("JIITPlacement.Models.App_Code.JobEligibilityCourseRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SysJobUuid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("posteddatetime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("updateddatetime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SysJobUuid");

                    b.ToTable("JobEligibilityCourses");
                });

            modelBuilder.Entity("JIITPlacement.Models.App_Code.JobEligibilityRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Criteria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SysJobUuid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("posteddatetime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("updateddatetime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SysJobUuid");

                    b.ToTable("JobEligibilities");
                });

            modelBuilder.Entity("JIITPlacement.Models.App_Code.JobGenderRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SysJobUuid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("posteddatetime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("updateddatetime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SysJobUuid");

                    b.ToTable("JobGenders");
                });

            modelBuilder.Entity("JIITPlacement.Models.App_Code.JobHiringFlowRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Sequence")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StageName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SysJobUuid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("posteddatetime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("updateddatetime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SysJobUuid");

                    b.ToTable("JobHiringFlows");
                });

            modelBuilder.Entity("JIITPlacement.Models.App_Code.JobRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("JobDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("JobProfile")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("Package")
                        .HasColumnType("real");

                    b.Property<string>("PackageInfo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlacementCategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlacementCategoryCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlacementType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SuperSetJobIdentifier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("posteddatetime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("updateddatetime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SuperSetJobIdentifier")
                        .IsUnique();

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("JIITPlacement.Models.App_Code.JobSkillRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SysJobUuid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("posteddatetime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("updateddatetime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SysJobUuid");

                    b.ToTable("JobSkills");
                });

            modelBuilder.Entity("JIITPlacement.Models.App_Code.NoticeRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SuperSetIdentifier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("posteddatetime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("updateddatetime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SuperSetIdentifier")
                        .IsUnique();

                    b.ToTable("Notices");
                });

            modelBuilder.Entity("JIITPlacement.Models.App_Code.SupersetAccount", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Batch")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CollegeCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Uuid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("posteddatetime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("updateddatetime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Uuid")
                        .IsUnique();

                    b.ToTable("SupersetAccounts");
                });
#pragma warning restore 612, 618
        }
    }
}
