// <auto-generated />
using System;
using JIITPlacement.Models.App_Code;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JIITPlacement.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260919191612_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JIITPlacement.Models.App_Code.JobDocumentRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DocumentIdentifier")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("DocumentUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<int>("JobRecordId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DocumentIdentifier")
                        .IsUnique();

                    b.HasIndex("JobRecordId");

                    b.ToTable("JobDocuments");
                });

            modelBuilder.Entity("JIITPlacement.Models.App_Code.JobEligibilityCourseRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("JobRecordId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("JobRecordId");

                    b.ToTable("JobEligibilityCourses");
                });

            modelBuilder.Entity("JIITPlacement.Models.App_Code.JobEligibilityRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("Criteria")
                        .HasColumnType("real");

                    b.Property<int>("JobRecordId")
                        .HasColumnType("integer");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("JobRecordId");

                    b.ToTable("JobEligibilities");
                });

            modelBuilder.Entity("JIITPlacement.Models.App_Code.JobGenderRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("JobRecordId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("JobRecordId");

                    b.ToTable("JobGenders");
                });

            modelBuilder.Entity("JIITPlacement.Models.App_Code.JobHiringFlowRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("JobRecordId")
                        .HasColumnType("integer");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<string>("StageName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("JobRecordId");

                    b.ToTable("JobHiringFlows");
                });

            modelBuilder.Entity("JIITPlacement.Models.App_Code.JobRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("JobDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("JobProfile")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<float>("Package")
                        .HasColumnType("real");

                    b.Property<string>("PackageInfo")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("PlacementCategory")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("PlacementCategoryCode")
                        .HasColumnType("integer");

                    b.Property<string>("PlacementType")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SuperSetJobIdentifier")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SuperSetJobIdentifier")
                        .IsUnique();

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("JIITPlacement.Models.App_Code.JobSkillRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("JobRecordId")
                        .HasColumnType("integer");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("JobRecordId");

                    b.ToTable("JobSkills");
                });

            modelBuilder.Entity("JIITPlacement.Models.App_Code.NoticeRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SuperSetIdentifier")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SuperSetIdentifier")
                        .IsUnique();

                    b.ToTable("Notices");
                });

            modelBuilder.Entity("JIITPlacement.Models.App_Code.SupersetAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Batch")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("CollegeCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Uuid")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Uuid")
                        .IsUnique();

                    b.ToTable("SupersetAccounts");
                });

            modelBuilder.Entity("JIITPlacement.Models.App_Code.JobDocumentRecord", b =>
                {
                    b.HasOne("JIITPlacement.Models.App_Code.JobRecord", "JobRecord")
                        .WithMany("Documents")
                        .HasForeignKey("JobRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobRecord");
                });

            modelBuilder.Entity("JIITPlacement.Models.App_Code.JobEligibilityCourseRecord", b =>
                {
                    b.HasOne("JIITPlacement.Models.App_Code.JobRecord", "JobRecord")
                        .WithMany("EligibilityCourses")
                        .HasForeignKey("JobRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobRecord");
                });

            modelBuilder.Entity("JIITPlacement.Models.App_Code.JobEligibilityRecord", b =>
                {
                    b.HasOne("JIITPlacement.Models.App_Code.JobRecord", "JobRecord")
                        .WithMany("EligibilityMarks")
                        .HasForeignKey("JobRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobRecord");
                });

            modelBuilder.Entity("JIITPlacement.Models.App_Code.JobGenderRecord", b =>
                {
                    b.HasOne("JIITPlacement.Models.App_Code.JobRecord", "JobRecord")
                        .WithMany("AllowedGenders")
                        .HasForeignKey("JobRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobRecord");
                });

            modelBuilder.Entity("JIITPlacement.Models.App_Code.JobHiringFlowRecord", b =>
                {
                    b.HasOne("JIITPlacement.Models.App_Code.JobRecord", "JobRecord")
                        .WithMany("HiringFlow")
                        .HasForeignKey("JobRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobRecord");
                });

            modelBuilder.Entity("JIITPlacement.Models.App_Code.JobSkillRecord", b =>
                {
                    b.HasOne("JIITPlacement.Models.App_Code.JobRecord", "JobRecord")
                        .WithMany("RequiredSkills")
                        .HasForeignKey("JobRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobRecord");
                });

            modelBuilder.Entity("JIITPlacement.Models.App_Code.JobRecord", b =>
                {
                    b.Navigation("AllowedGenders");

                    b.Navigation("Documents");

                    b.Navigation("EligibilityCourses");

                    b.Navigation("EligibilityMarks");

                    b.Navigation("HiringFlow");

                    b.Navigation("RequiredSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
