"""backend tables

Revision ID: e93c6591e1da
Revises: 
Create Date: 2026-09-27 13:36:27.702838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e93c6591e1da'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('raw_name', sa.Text(), nullable=True),
    sa.Column('aliases', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_companies'))
    )
    op.create_index(op.f('ix_companies_created_at'), 'companies', ['created_at'], unique=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=True)
    op.create_table('emails',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('gmail_message_id', sa.String(length=64), nullable=False),
    sa.Column('thread_id', sa.String(length=64), nullable=True),
    sa.Column('message_id_header', sa.String(length=512), nullable=True),
    sa.Column('in_reply_to', sa.String(length=512), nullable=True),
    sa.Column('source_group', sa.String(length=255), nullable=True),
    sa.Column('source_group_email', sa.String(length=255), nullable=True),
    sa.Column('sender', sa.Text(), nullable=True),
    sa.Column('sender_email', sa.String(length=320), nullable=True),
    sa.Column('recipient', sa.Text(), nullable=True),
    sa.Column('cc', sa.Text(), nullable=True),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('received_raw', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('body_clean', sa.Text(), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('has_attachments', sa.Boolean(), nullable=False),
    sa.Column('label_ids', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('cluster_key', sa.String(length=600), nullable=True),
    sa.Column('is_canonical', sa.Boolean(), nullable=False),
    sa.Column('dedup_of', sa.String(length=32), nullable=True),
    sa.Column('revision_of', sa.String(length=32), nullable=True),
    sa.Column('classification', sa.String(length=64), nullable=True),
    sa.Column('classification_confidence', sa.Float(), nullable=True),
    sa.Column('classification_signals', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('classification_method', sa.String(length=32), nullable=True),
    sa.Column('processing_status', sa.String(length=16), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dedup_of'], ['emails.id'], name=op.f('fk_emails_dedup_of_emails'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['revision_of'], ['emails.id'], name=op.f('fk_emails_revision_of_emails'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_emails'))
    )
    op.create_index(op.f('ix_emails_classification'), 'emails', ['classification'], unique=False)
    op.create_index(op.f('ix_emails_cluster_key'), 'emails', ['cluster_key'], unique=False)
    op.create_index(op.f('ix_emails_created_at'), 'emails', ['created_at'], unique=False)
    op.create_index(op.f('ix_emails_gmail_message_id'), 'emails', ['gmail_message_id'], unique=True)
    op.create_index(op.f('ix_emails_processing_status'), 'emails', ['processing_status'], unique=False)
    op.create_index(op.f('ix_emails_received_at'), 'emails', ['received_at'], unique=False)
    op.create_index(op.f('ix_emails_thread_id'), 'emails', ['thread_id'], unique=False)
    op.create_table('email_attachments',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('email_id', sa.String(length=32), nullable=False),
    sa.Column('gmail_attachment_id', sa.String(length=512), nullable=True),
    sa.Column('filename', sa.Text(), nullable=True),
    sa.Column('mime_type', sa.String(length=255), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('method', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], name=op.f('fk_email_attachments_email_id_emails'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_attachments')),
    comment='one row per (email, gmail attachment id)'
    )
    op.create_index(op.f('ix_email_attachments_email_id'), 'email_attachments', ['email_id'], unique=False)
    op.create_table('funnel_counts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('email_id', sa.String(length=32), nullable=False),
    sa.Column('company_id', sa.String(length=32), nullable=True),
    sa.Column('round_name', sa.Text(), nullable=False),
    sa.Column('round_order', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('method', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_funnel_counts_company_id_companies'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], name=op.f('fk_funnel_counts_email_id_emails'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_funnel_counts'))
    )
    op.create_index(op.f('ix_funnel_counts_company_id'), 'funnel_counts', ['company_id'], unique=False)
    op.create_index(op.f('ix_funnel_counts_created_at'), 'funnel_counts', ['created_at'], unique=False)
    op.create_index(op.f('ix_funnel_counts_email_id'), 'funnel_counts', ['email_id'], unique=False)
    op.create_table('offers',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('email_id', sa.String(length=32), nullable=False),
    sa.Column('company_id', sa.String(length=32), nullable=True),
    sa.Column('role', sa.Text(), nullable=True),
    sa.Column('employment_type', sa.String(length=64), nullable=True),
    sa.Column('duration', sa.Text(), nullable=True),
    sa.Column('stipend', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('ctc_total', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('ctc_raw', sa.Text(), nullable=True),
    sa.Column('ctc_basis', sa.String(length=16), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('method', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_offers_company_id_companies'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], name=op.f('fk_offers_email_id_emails'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_offers'))
    )
    op.create_index(op.f('ix_offers_company_id'), 'offers', ['company_id'], unique=False)
    op.create_index(op.f('ix_offers_created_at'), 'offers', ['created_at'], unique=False)
    op.create_index(op.f('ix_offers_email_id'), 'offers', ['email_id'], unique=False)
    op.create_table('opportunities',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('email_id', sa.String(length=32), nullable=False),
    sa.Column('company_id', sa.String(length=32), nullable=True),
    sa.Column('organization_name', sa.Text(), nullable=True),
    sa.Column('event_name', sa.Text(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=True),
    sa.Column('stages', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('eligibility', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('team_rules', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('links', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('registration_link', sa.Text(), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('career_note', sa.Text(), nullable=True),
    sa.Column('is_revision_of', sa.String(length=32), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('method', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_opportunities_company_id_companies'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], name=op.f('fk_opportunities_email_id_emails'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['is_revision_of'], ['emails.id'], name=op.f('fk_opportunities_is_revision_of_emails'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_opportunities'))
    )
    op.create_index(op.f('ix_opportunities_company_id'), 'opportunities', ['company_id'], unique=False)
    op.create_index(op.f('ix_opportunities_created_at'), 'opportunities', ['created_at'], unique=False)
    op.create_index(op.f('ix_opportunities_deadline'), 'opportunities', ['deadline'], unique=False)
    op.create_index(op.f('ix_opportunities_email_id'), 'opportunities', ['email_id'], unique=False)
    op.create_index(op.f('ix_opportunities_event_type'), 'opportunities', ['event_type'], unique=False)
    op.create_table('shortlist_events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('email_id', sa.String(length=32), nullable=False),
    sa.Column('company_id', sa.String(length=32), nullable=True),
    sa.Column('stage', sa.String(length=64), nullable=False),
    sa.Column('stage_raw', sa.Text(), nullable=True),
    sa.Column('venue', sa.Text(), nullable=True),
    sa.Column('reporting_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('selection_process', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('interview_dates', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('method', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_shortlist_events_company_id_companies'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], name=op.f('fk_shortlist_events_email_id_emails'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shortlist_events'))
    )
    op.create_index(op.f('ix_shortlist_events_company_id'), 'shortlist_events', ['company_id'], unique=False)
    op.create_index(op.f('ix_shortlist_events_created_at'), 'shortlist_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_shortlist_events_email_id'), 'shortlist_events', ['email_id'], unique=False)
    op.create_table('student_placement_events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('roll_no', sa.String(length=64), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('company_id', sa.String(length=32), nullable=True),
    sa.Column('email_id', sa.String(length=32), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('stage', sa.Text(), nullable=True),
    sa.Column('normalized_status', sa.String(length=32), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('method', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_student_placement_events_company_id_companies'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], name=op.f('fk_student_placement_events_email_id_emails'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_placement_events')),
    sa.UniqueConstraint('email_id', 'roll_no', 'event_type', name='uq_student_placement_events_email')
    )
    op.create_index(op.f('ix_student_placement_events_company_id'), 'student_placement_events', ['company_id'], unique=False)
    op.create_index(op.f('ix_student_placement_events_created_at'), 'student_placement_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_student_placement_events_email_id'), 'student_placement_events', ['email_id'], unique=False)
    op.create_index(op.f('ix_student_placement_events_event_type'), 'student_placement_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_student_placement_events_normalized_status'), 'student_placement_events', ['normalized_status'], unique=False)
    op.create_index(op.f('ix_student_placement_events_roll_no'), 'student_placement_events', ['roll_no'], unique=False)
    op.create_table('offer_students',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('offer_id', sa.String(length=32), nullable=False),
    sa.Column('roll_no', sa.String(length=64), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('branch', sa.Text(), nullable=True),
    sa.Column('program', sa.Text(), nullable=True),
    sa.Column('college', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('role', sa.Text(), nullable=True),
    sa.Column('status_raw', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], name=op.f('fk_offer_students_offer_id_offers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_offer_students'))
    )
    op.create_index(op.f('ix_offer_students_offer_id'), 'offer_students', ['offer_id'], unique=False)
    op.create_index(op.f('ix_offer_students_roll_no'), 'offer_students', ['roll_no'], unique=False)
    op.create_table('shortlist_students',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('shortlist_event_id', sa.String(length=32), nullable=False),
    sa.Column('roll_no', sa.String(length=64), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('branch', sa.Text(), nullable=True),
    sa.Column('program', sa.Text(), nullable=True),
    sa.Column('college', sa.Text(), nullable=True),
    sa.Column('status_raw', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['shortlist_event_id'], ['shortlist_events.id'], name=op.f('fk_shortlist_students_shortlist_event_id_shortlist_events'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shortlist_students'))
    )
    op.create_index(op.f('ix_shortlist_students_roll_no'), 'shortlist_students', ['roll_no'], unique=False)
    op.create_index(op.f('ix_shortlist_students_shortlist_event_id'), 'shortlist_students', ['shortlist_event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shortlist_students_shortlist_event_id'), table_name='shortlist_students')
    op.drop_index(op.f('ix_shortlist_students_roll_no'), table_name='shortlist_students')
    op.drop_table('shortlist_students')
    op.drop_index(op.f('ix_offer_students_roll_no'), table_name='offer_students')
    op.drop_index(op.f('ix_offer_students_offer_id'), table_name='offer_students')
    op.drop_table('offer_students')
    op.drop_index(op.f('ix_student_placement_events_roll_no'), table_name='student_placement_events')
    op.drop_index(op.f('ix_student_placement_events_normalized_status'), table_name='student_placement_events')
    op.drop_index(op.f('ix_student_placement_events_event_type'), table_name='student_placement_events')
    op.drop_index(op.f('ix_student_placement_events_email_id'), table_name='student_placement_events')
    op.drop_index(op.f('ix_student_placement_events_created_at'), table_name='student_placement_events')
    op.drop_index(op.f('ix_student_placement_events_company_id'), table_name='student_placement_events')
    op.drop_table('student_placement_events')
    op.drop_index(op.f('ix_shortlist_events_email_id'), table_name='shortlist_events')
    op.drop_index(op.f('ix_shortlist_events_created_at'), table_name='shortlist_events')
    op.drop_index(op.f('ix_shortlist_events_company_id'), table_name='shortlist_events')
    op.drop_table('shortlist_events')
    op.drop_index(op.f('ix_opportunities_event_type'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_email_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_deadline'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_created_at'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_company_id'), table_name='opportunities')
    op.drop_table('opportunities')
    op.drop_index(op.f('ix_offers_email_id'), table_name='offers')
    op.drop_index(op.f('ix_offers_created_at'), table_name='offers')
    op.drop_index(op.f('ix_offers_company_id'), table_name='offers')
    op.drop_table('offers')
    op.drop_index(op.f('ix_funnel_counts_email_id'), table_name='funnel_counts')
    op.drop_index(op.f('ix_funnel_counts_created_at'), table_name='funnel_counts')
    op.drop_index(op.f('ix_funnel_counts_company_id'), table_name='funnel_counts')
    op.drop_table('funnel_counts')
    op.drop_index(op.f('ix_email_attachments_email_id'), table_name='email_attachments')
    op.drop_table('email_attachments')
    op.drop_index(op.f('ix_emails_thread_id'), table_name='emails')
    op.drop_index(op.f('ix_emails_received_at'), table_name='emails')
    op.drop_index(op.f('ix_emails_processing_status'), table_name='emails')
    op.drop_index(op.f('ix_emails_gmail_message_id'), table_name='emails')
    op.drop_index(op.f('ix_emails_created_at'), table_name='emails')
    op.drop_index(op.f('ix_emails_cluster_key'), table_name='emails')
    op.drop_index(op.f('ix_emails_classification'), table_name='emails')
    op.drop_table('emails')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_created_at'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
